#
# Scrutinizer code analysis for PHP.
#
# https://scrutinizer-ci.com/docs/guides/php/
# https://scrutinizer-ci.com/docs/guides/php/continuous-integration-deployment
# https://scrutinizer-ci.com/docs/tools/php/php-scrutinizer/
# https://scrutinizer-ci.com/docs/tools/php/php-scrutinizer/checks


filter:

  # Everything in a root level "test" directory will be excluded
  excluded_paths:
    - "test/"

  # Everything in a root level "vendor" directory will be excluded from analysis
  # but treated as a dependency
  dependency_paths:
    - "vendor/"


before_commands:
  - "composer install --dev --prefer-source"


# Use new PHP Analysis Engine.
# https://scrutinizer-ci.com/docs/tools/php/php-analyzer/guides/migrate_to_new_php_analysis
build:
  nodes:
    analysis:
      environment:
        php:
          version: 7.4
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - phpcs-run --standard=.phpcs.xml


# https://scrutinizer-ci.com/docs/tools/external-code-coverage/
tools:
  external_code_coverage: true
