name: Docs

on:
  workflow_dispatch:
  pull_request: ~
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'

jobs:
  documentation:
    name: Build docs on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:

      - name: Acquire sources
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build docs
        run: |
          cd docs && make check
